### DISCUSSION TITLE
Enhancing Credential Configuration in CRDs: Leveraging Environment Variables

### DISCUSSION THREAD

**Discussion by geoffrey1330** [TykTechnologies/tyk-operator#660] [Ideas]
**Description:**
This discussion centers around improving the management of credential configurations in Kubernetes Custom Resource Definitions (CRDs), particularly addressing the need to securely handle sensitive information like API keys within the CRD's YAML files. Currently, there's a requirement to place such credentials in the config_data section of an API definition within CRDs.

**Objective:**
The primary goal is to explore better ways to handle credentials and secrets in CRDs to enhance security and ease of use. It would be beneficial to discuss potential solutions and existing methods.

**Proposed Approach:**
One potential approach to consider is adopting a mechanism similar to how Kubernetes handles secrets and ConfigMaps in Deployments. This could include leveraging environment variables in CRD YAML files for secure credential management.

i.e 
```
    env:
    - name: <env_name>
      valueFrom:
        secretKeyRef:
          name: <secret_name>
          key: <secret_data_key>
```

**Comment by jonathanfoster** [comment]
Hey @geoffrey1330, thanks for taking the lead on this. I definitely have use cases for this feature and I’ve been watching the issue for a while.

I like the idea of using the existing ConfigMap pattern in Deployments. This is definitely a more k8s native approach.

I would also consider maintaining compatibility with existing [Tyk KV secrets storage](https://tyk.io/docs/tyk-configuration-reference/kv-store/) so external KV stores can still be used. This would prevent any incompatibility issues when migrating from JSON API definitions.

Let me see if I can create some test API definitions based on my use cases.

**Comment by jonathanfoster** [comment]
Here's a use case I encounter quite often.

```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-bearer
spec:
  name: httpbin-bearer
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org/bearer
    listen_path: /httpbin/bearer
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
        global_headers:
          authorization: $secret_env.httpbin_bearer_auth
```

**Reply by geoffrey1330** [reply]
Alright still need to have discussion with contributors on the best way to approach this

**Comment by geoffrey1330** [comment]
Hi @buraksekili I have created a PR for the api structure [here](https://github.com/TykTechnologies/tyk-operator/pull/661)

**Comment by buraksekili** [comment]
Thank you for raising this concern.

Presently, we employ Kubernetes Secret references for specific fields like [PinnedPublicKeysRefs](https://github.com/TykTechnologies/tyk-operator/blob/463aaec695e6631ec163f334351f87962404b819/api/model/api.go#L656), which are not part of the typical API Definition within Tyk. When the operator detects these fields with populated values, it retrieves the corresponding secret from Kubernetes. Subsequently, it creates a secret within Tyk using Tyk APIs and uses the ID of the newly created secret in the APIDefinition.

To illustrate this operation more explicitly, here's a rough scenario:

```yaml
# apidefinition.yaml
spec:
   fooRef: mysecret 
```

Upon applying this manifest, the operator:
- Retrieves the Kubernetes Secret named `mysecret`
- Uploads the content of `mysecret` to Tyk
- Obtains the ID of the secret created on Tyk (let's assume the ID is 123)
- Assigns `.spec.foo` to `123`

Consequently, the resulting structure becomes:

```yaml
# apidefinition.yaml
spec:
   fooRef: mysecret
   foo: 123
```

This flow allows your API to successfully utilize your Kubernetes secret.

The challenge I've observed while employing secrets in Config Data is due to its nature as an arbitrary JSON, as outlined [here](https://github.com/TykTechnologies/tyk-operator/blob/463aaec695e6631ec163f334351f87962404b819/api/model/api.go#L835). As it lacks a JSON schema, we face difficulty in marshaling the structure into a Go structure to inherently comprehend Kubernetes references within it. While we could consider hacky solutions to support this concept, it might restrict the potential use cases of Config Data, which we aim to avoid. Thus, we are unable to directly reference a secret using fields like `valueFrom` in the Config Data. I'm open to discussing potential implementation ideas to address this constraint.

**Reply by geoffrey1330** [reply]
We could consider creating another field in the struct called `Env` to deal with handling secret and configMap data.
so we could have something
```
# apidefinition.yaml
spec:
   env:
   - name: <env_name>
      valueFrom:
          secretKeyRef:
              name: <secret_name>
              key: <secret_data_key>
   
   - name: <env_name>
      valueFrom:
         configMapKeyRef:
            name: <configmap_name>
            key: <configmap_data_key>
```

**Reply by buraksekili** [reply]
While I understand the logic behind suggesting the use of `Env` to update environment variables, the challenge lies in managing updates to `Config Data`.
`Config Data`, being an arbitrary JSON object, lacks a defined structure known to the Operator. Therefore, once users declare environment variables via `Env`, the task remains: how do we know the fields requiring updates in the raw JSON object?

Assume that I have following ApiDefinition CRs:

```yaml
spec:
   config_data:
           firstField: something
           secondField:
                 env:
                   - name: <env_name>
                   ...          
```

```yaml
spec:
   config_data:
           completelyDifferentField:
                 otherSubField:
                     env:
                     - name: <env_name>
                       ...          
```

So, users are free to declare `config_data` in any format. Now, my concern is updating such unstructured data.

**Reply by geoffrey1330** [reply]
We could introduce another struct in the config_data which will be optional 
```
type MapStringInterfaceType struct {
    // +kubebuilder:pruning:PreserveUnknownFields
    unstructured.Unstructured `json:",inline"`
    
    // +optional
   Env *EnvVariable `json:"env,omitempty"`
}
```

**Comment by geoffrey1330** [comment]
Hi @buraksekili base on the look of things the env approach might not be the best solution.
But proposing a new approach which allow users to securely reference secrets in Kubernetes ApiDefinition configurations using `$secret.<SecretName>.<SecretKey>`, streamlining secret management by dynamically fetching values during runtime.

i.e 
it fetches the value of this secret base on the secretName and secretKey reference in the yaml.
```
  ...
        global_headers:
          authorization: $secret.tykSecret.httpbin_bearer_auth
```

**Reply by buraksekili** [reply]
While this could be a potential solution, we would still face challenges in parsing [Unstructured data](https://github.com/TykTechnologies/tyk-operator/blob/463aaec695e6631ec163f334351f87962404b819/api/model/api.go#L39C2-L39C28), where values are stored as `interface{}`. So, in my opinion the real problem is deciding on how to parse such unstructured data and how to understand that users refer to external resources in this unstructured data.

Additionally, I prefer adhering to Kubernetes Community standards. According to [API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#object-references-examples), instead of referencing secrets directly, it's recommended to introduce a new field, such as `secretRef`, to obtain the metadata information of the secret.

**Reply by geoffrey1330** [reply]
Alright I will make more research on this.

**Reply by komalsukhani** [reply]
@geoffrey1330 Wanted to confirm you will be implement using the `$secret` field approach right?

**Reply by geoffrey1330** [reply]
Yes I will Implement it using the approach you suggested once i get the go ahead from your end

**Reply by komalsukhani** [reply]
Great! Good to go then.

**Reply by geoffrey1330** [reply]
Just to be clear on the expectation. we reference the secret in the config_data and then retrieve this secret key and value, append it to the config_data as fields right?

**Reply by komalsukhani** [reply]
I would suggest to add a new field, something like config_data_ref, to accept secret name. Operator will read the secret and populate the config_data while sending a request to Tyk Gateway/Dashboard.

**Reply by geoffrey1330** [reply]
Hi @komalsukhani I have been out for while.
Will resume working on this proposed solution this week.

**Comment by geoffrey1330** [comment]
Hi @buraksekili i'm facing some difficulties try to deploy the operator for development purposes so i could test my implementation. 
this [doc](https://github.com/TykTechnologies/tyk-operator/blob/master/docs/development.md) doesn't work me

**Reply by buraksekili** [reply]
can you please raise a new issue with the details of problems you faced?

**Comment by geoffrey1330** [comment]
Hi @buraksekili what do you think about this new approach.

The Approach will address concerns related to parsing Unstructured data by using a recursive traversal approach to handle nested structures with values stored as interface{}. Additionally, it identifies secretRef by checking for the presence of a field with that name in the Unstructured data. Once secretRef is detected, it retrieves the secret based on the specified name and key within the secretRef.

**Reply by geoffrey1330** [reply]
@buraksekili this is what i meant.
```
spec:
   config_data:
           firstField: something
           secondField:
                 secretRef:
                   - name: <secret_ name>
                   - key: <secret_data_key>
                   ...          
```

after the recursive traversal. it becomes like this.

```
spec:
   config_data:
           firstField: something
           secondField: <secret_data_value>
                   ...          
```
