### ISSUE TITLE
ingress without template should create simple keyless api definition

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#212]
It should not be mandatory to apply a template API Definition.
The most basic ingress object should be enough to create a keyless API Definition.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
spec:
  rules:
    - host: httpbin.ahmet
      http:
        paths:
          - path:
            pathType: Prefix
            backend:
              service:
                name: httpbin
                port:
                  number: 8000
```

At the moment, the template annotation in the ingress route is mandatory:

```
	// ensure there is a template api definition
	templateAnnotationValue, ok := desired.Annotations[ingressTemplateAnnotationKey]
	if !ok {
		return ctrl.Result{}, fmt.Errorf("expecting template annotation %s", ingressTemplateAnnotationKey)
	}
```

This causes issues with cert-manager creating ingress resources as we currently require:

```
# annoying annotations which means if the API Definitions are protected (not keyless), then we cannot enable TLS
acme.cert-manager.io/http01-edit-in-place: "true"
```

```
# funky hacks to handle the acme-http challenge

			if !strings.Contains(p.Path, ".well-known/acme-challenge") && !strings.Contains(p.Backend.ServiceName, "cm-acme-http-solver") {
				for _, tls := range desired.Spec.TLS {
					for _, host := range tls.Hosts {
						if hostName == host {
							api.Spec.Protocol = "https"
							api.Spec.CertificateSecretNames = []string{
								tls.SecretName,
							}
							api.Spec.ListenPort = 443
						}
					}
				}
			} else {
				// for the acme challenge
				api.Spec.Proxy.StripListenPath = false
				api.Spec.Proxy.PreserveHostHeader = true
			}
```
