### ISSUE TITLE
JWT default policy key creation issue

### ISSUE THREAD

**Issue by Jesse0Michael** [TykTechnologies/tyk-operator#257]
I was testing the v0.5.0 changes locally that included the JWT auth changes: 
https://github.com/TykTechnologies/tyk-operator/pull/248

And it appears the API Definition is linked to the Security Policy, but when making a request through the gateway I get
```
{
    "error": "failed to create key: policy not found: \"YXBpL3JlcG9ydHMtYXBpLXNlY3VyaXR5LXBvbGljeQ==\""
}
```
cc @gernest 

## Expected Behavior

Expected to make it through the tyk gateway and reach the API

## Current Behavior

500 Internal Service Error for key creation by policy

## Possible Solution

It seems that the wrong ID might be linked.. possibly..?

## Steps to Reproduce

I have an API Definition CRD that looks like
```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: {{ .Values.app.name }}-api-definition
spec:
  name: {{ .Values.app.name }}
  active: true
  use_keyless: false
  protocol: "http"
  proxy:
    target_url: http://{{ .Values.app.name }}.api:80
    listen_path: {{ .Values.app.ingress.path }}
    strip_listen_path: true
  enable_jwt: true
  jwt_signing_method: rsa
  jwt_source: {{ .Values.auth.jwtSource }}
  jwt_identity_base_field: sub
  jwt_policy_field_name: pol
  jwt_default_policies:
    - {{ .Release.Namespace }}/{{ .Values.app.name }}-security-policy

```

And a Security Policy CRD
```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.app.name }}-security-policy
spec:
  name: {{ .Values.app.name }}
  state: active
  active: true
  access_rights_array:
    - name: {{ .Values.app.name }}-api-definition
      namespace: {{ .Release.Namespace }}
      versions:
        - Default

```

Which creates an API DEFINITION
``` json
...
                "jwt_identity_base_field": "sub",
                "jwt_client_base_field": "",
                "jwt_policy_field_name": "pol",
                "jwt_default_policies": [
                    "YXBpL3JlcG9ydHMtYXBpLXNlY3VyaXR5LXBvbGljeQ=="
                ],
...
```
and a POLICY
```json
            "_id": "602c0ff4c242530001d6b027",
            "id": "YXBpL3JlcG9ydHMtYXBpLXNlY3VyaXR5LXBvbGljeQ==",
            "name": "reports-api",
            "org_id": "602c07d6c242530001d6b021",
```

But when testing the gateway with a proper JWT token I get the 500 response
```json
{
    "error": "failed to create key: policy not found: \"YXBpL3JlcG9ydHMtYXBpLXNlY3VyaXR5LXBvbGljeQ==\""
}
```

If I hard code the `jwt_default_policies` to `602c0ff4c242530001d6b027` I get through the gateway no problem... so maybe `_id` needs to be linked? not `id`? just guessing.

## Context

In a local K3D kubernetes enviornment, I am using  https://github.com/TykTechnologies/tyk-helm-chart along side https://github.com/TykTechnologies/tyk-operator

## Your Environment

* OS (e.g. Linux, macOS, Windows):
  * OS version: macOS
* `tyk-operator` version/commit: v0.5.0

PLEASE let me know if I'm doing something wrong, or if it might be my Tyk version, or something like that

**Comment by gernest** [comment]
Looking at ypur SecurityPolicy, it seems it is missing `namespace`. I think it should look like this

```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Values.app.name }}-security-policy
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.app.name }}
  state: active
  active: true
  access_rights_array:
    - name: {{ .Values.app.name }}-api-definition
      namespace: {{ .Release.Namespace }}
      versions:
        - Default
   ```

This will match with how you reference it.
