### ISSUE TITLE
[TT-4978] - Specify Method for API Definition

### ISSUE THREAD

**Issue by certino-simonchapman** [TykTechnologies/tyk-operator#416]
Currently whilst able to create API Definitions, you are unable to specify the allowed methods. This means you're half in and half out with using the endpoint designer to complete situations where you don't want all and sundry to access your methods (for example GET only publicly, and POST only internally).

## Expected Behavior
```yaml
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 80
      allowed_methods: [GET, POST, DELETE]
  selector:
    app: httpbin
```

## Current Behavior
Currently creating new API definitions don't allow specification of allowed methods. You need to manually change this in the endpoint designer making the endpoints out of sync with IaC.

It is a frustrating and repeated step prohibiting staying on a clear and clean path of how to manage API definitions. Having to juggle the two and remember to make these changes frequently leaves open risk of deployment failures.

## Possible Solution
adding the additional parameter to the API definition and corresponding API modules.
