### ISSUE TITLE
[TT-5089] - Attempting to remove an ApiDefinition fails if previously associated to a SecurityPolicy

### ISSUE THREAD

**Issue by benewen-brav** [TykTechnologies/tyk-operator#431]
Tyk Hybrid Gateway Version: 3.2.1
Tyk Cloud Gateway Dashboard Version: 3.2.0
Tyk Operator Version: 0.8.2

Full logs attached [logs.zip](https://github.com/TykTechnologies/tyk-operator/files/8453758/logs.zip)

Reproduction steps:

1. Create an ApiDefinition and SecurityPolicy that are associated

```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin protected
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
```

```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin
spec:
  id: 62505570b6e263000139f7ea
  name: Httpbin Security Policy
  state: active
  active: true
  access_rights_array:
    - name: httpbin
      namespace: default
      versions:
        - Default
```
2.  Remove the `access_rights_array` from the SecurityPolicy.
3.  Attempt to remove the ApiDefinition, but this error is returned:
```bash
{"level":"info","ts":1649434399.083711,"logger":"controllers.ApiDefinition","msg":"checking linked security policies"}
{"level":"error","ts":1649434399.0837798,"logger":"controller-runtime.manager.controller.apidefinition","msg":"Reconciler error","reconciler group":"tyk.tyk.io","reconciler kind":"ApiDefinition","name":"httpbin","namespace":"default","error":"unable to delete api due to security policy dependency=default/httpbin","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/internal/controller/controller.go:214"}
{"level":"info","ts":1649434401.644129,"logger":"controllers.ApiDefinition","msg":"Reconciling ApiDefinition instance","ApiDefinition":"default/httpbin"}
{"level":"info","ts":1649434401.6443067,"logger":"controllers.ApiDefinition","msg":"resource being deleted"}
``` 

It appears that removing the API from the `access_rights_array` does not properly remove the SecurityPolicy from the `linked_by_policies` in the ApiDefinition:

```yaml
  linked_by_policies:
    Name:       httpbin
    Namespace:  default
```
