### ISSUE TITLE
[TT-5237] Creating a new security policy which is reconciled by the operator has mismatched IDs

### ISSUE THREAD

**Issue by jdieterich-brav** [TykTechnologies/tyk-operator#434]
## Expected Behavior
When we create a new security policy and deploy it to our k8s cluster, the operator will pick this up, and push it up to the dashboard. From here we can use the policy to generate keys for it, add APIs etc.

## Current Behavior
The security policy is picked up by the operator and pushed to the dashboard. However when we then try to generate a key for example, we get an error message that the policy isn't found, and the ID associated with it. However this ID doesn't match with the ID that is presented in the dashboard. When we inspect the security policy in our cluster, the `pol_id` value is set to the ID that is displayed on the dashboard, whereas `_id` is set to the ID it can't find on key generation. It looks like this ID is `<namespace>/<apiName>` encoded in base64.

## Possible Solution
When the operator pushed the security policy it get's the ID back from the dashboard and then updates `_id` to match that value.

## Steps to Reproduce
1. Have a k8s cluster with the operator and hybrid gateway deployed
2. Create a security policy in the cluster
3. Try to generate a key for the policy

## Context
We are looking to add security policies in a gitops way, by adding them to a repo, which then reconciles them to the cluster through the use of flux. We would like to then be able to use these policies without having to change any config on the dashboard.

## Your Environment
* OS: Linux 
* Tyk Hybrid Gateway Version: 3.2.1
* Tyk Cloud Gateway Dashboard Version: 3.2.0
* Tyk Operator Version: 0.8.2

**Comment by komalsukhani** [comment]
I am not able to reproduce this.
Can you please share Security Policy yaml file?

**Comment by jdieterich-brav** [comment]
`apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: tenants
  namespace: flux-system
spec:
  id: 62500c5fb6e263000139f791
  name: tenants
  active: true
  state: active
  access_rights_array:
    - name: internal-developer-platform-internal-developer-platform-a86b6fab5
      namespace: internal-developer-platform
      versions:
        - Default`
This is the policy, we added the ID into the spec later, so initially that wasn't part of it

**Comment by jdieterich-brav** [comment]
```
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: tenants
  namespace: flux-system
spec:
  id: 62500c5fb6e263000139f791
  name: tenants
  active: true
  state: active
  access_rights_array:
    - name: internal-developer-platform-internal-developer-platform-a86b6fab5
      namespace: internal-developer-platform
      versions:
        - Default
```
This is the file, however the initial policy didn't have the ID, that was added later
