### ISSUE TITLE
TT-7112 Add Basic Authentication option to ApiDefinition CRD

### ISSUE THREAD

**Issue by bogumillaska** [TykTechnologies/tyk-operator#534]
Please add Basic Authentication option. 

## Expected Behavior
Add and support Basic Authentication configuration in api definition CRD.

### Potential BDD Test Coverage

```gherkin
Feature:  Basic Authentication configuration
  As a Developer
  I want enable basic authentication on an API definition
  So that basic authentication is required during API execution

  Scenario: basic authentication enabled and basic authentication header provided
    Given there is a httpbin-basic-auth.yaml with use_basic_auth : true
    When that api definition is applied 
    And I request /httpbin-basic-auth/get with basic authentication http header 
    Then I should receive 200 HTTP response

  Scenario: basic authentication enabled and basic authentication header not provided
    Given there is a httpbin-basic-auth.yaml with use_basic_auth : true
    When that api definition is applied 
    And I request /httpbin-basic-auth/get without basic authentication http header 
    Then I should receive 403 HTTP response
```

## Current Behavior
Basic authentication is still on the waiting list of features.

## Possible Solution
Add support for  use_basic_auth configuration option in api definition CRD
```yaml
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-basic-auth
spec:
  name: Httpbin Basic Authentication
  protocol: https
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
  version_data:
    default_version: Default
    not_versioned: true
    versions:
      Default:
        name: Default
  use_basic_auth: true
```
