### ISSUE TITLE
method_transforms to_method works randomly

### ISSUE THREAD

**Issue by mkyc** [TykTechnologies/tyk-operator#542]
with `tyk.tyk.io/v1alpha1` `ApiDefinition` when I setup `extended_paths.method_transforms.method GET -> to_method POST` as described [in here](https://github.com/TykTechnologies/tyk-operator/blob/master/bdd/custom_resources/transform/method.yaml) result is random. 

## Expected Behavior

when I run echo server and curl -X GET I should see POST being delivered to echo server pod. 

## Current Behavior

only one in every call gets transformed do POST method

## Steps to Reproduce

Test stub:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: echo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: echo
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: echo
  namespace: echo
spec:
  name: echo
  use_keyless: true
  protocol: http
  active: true
  domain: echo.example.com
  proxy:
    target_url: http://echo.echo.svc:8080
    listen_path: /foo
    strip_listen_path: true
  version_data:
    default_version: v1
    not_versioned: true
    versions:
      v1:
        name: v1
        use_extended_paths: true
        paths:
          black_list: []
          ignored: []
          white_list: []
        extended_paths:
          method_transforms:
            - path: /bar
              method: GET
              to_method: POST
```

Test script: 

```shell
#!/bin/bash
for i in {0..50}
do
  sleep 1
  date +"%T"
  curl --silent https://echo.example.com/foo/bar -X GET | jq -r '.http.method'
done
```

Result: 
```text
15:24:38
GET
15:24:40
GET
15:24:41
GET
15:24:42
GET
15:24:43
GET
15:24:45
POST << --- here
15:24:46
GET
15:24:47
POST << --- here
15:24:49
GET
15:24:50
GET
15:24:51
GET
15:24:52
GET
15:24:54
GET
15:24:55
GET
15:24:56
GET
15:24:57
GET
15:24:59
POST << --- here
15:25:00
GET
15:25:01
GET
15:25:03
GET
15:25:04
GET
15:25:05
GET
15:25:06
GET
15:25:08
GET
15:25:09
GET
15:25:10
GET
15:25:11
GET
15:25:13
GET
15:25:14
GET
15:25:15
GET
15:25:17
GET
15:25:18
GET
15:25:19
GET
15:25:20
GET
15:25:22
GET
15:25:23
POST << --- here
15:25:24
GET
15:25:25
GET
15:25:27
POST << --- here
15:25:28
GET
15:25:29
GET
15:25:31
GET
15:25:32
POST << --- here
15:25:33
GET
15:25:34
GET
15:25:36
GET
15:25:37
GET
15:25:38
GET
15:25:40
GET
15:25:41
GET
15:25:42
GET

```

## Your Environment

* `tyk-operator` chart version: 0.12.0
* `tyk-headless` chart version: 0.13.1

**Comment by buraksekili** [comment]
hi @mkyc , thank you for raising this issue. I see that you use `tyk-headless` which deploys Tyk Gateway as `DaemonSet` by default. For reference, you can check [tyk-helm-chart repository](https://github.com/TykTechnologies/tyk-helm-chart/tree/master/tyk-headless#installation).
So, if you have multiple replicas of the gateway, this might cause the issue because as far as I understand, Tyk Operator completed its responsibility, which is creating corresponding resources (in this case ApiDefinition) on Tyk Gateway. 

Can you please check kind of Tyk Gateway? If it is `DaemonSet`, can you please try updating the type with `DaemonSet` and try again?

**Comment by mkyc** [comment]
Hi, I can confirm that Tyk Gateway is installed as Deployment. Here is `values.yaml` file for Helm Chart. 

```yaml
redis:
  addrs:
  - tyk-redis-master.tyk.svc.cluster.local:6379
  pass: REDACTED

gateway:
  hostName: ""
  tls: false

  kind: Deployment

secrets:
  APISecret: LALALA
  OrgID: NANANA
```
