### ISSUE TITLE
Operator deletes graphql schema if not provided

### ISSUE THREAD

**Issue by taylorsmithgg** [TykTechnologies/tyk-operator#587]
When deploying the following ApiDefinition w/apollo router, Tyk detects a schema on launch, but does not apply it.

It would be helpful to have an "auto sync" for discovered schemas instead of manually specifying them in the ApiDefinition.

After reconciliation, it will delete this schema, leaving it empty as it is not provided in the ApiDefinition.

```
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: router
spec:
  active: true
  name: router
  use_keyless: true
  protocol: http
  graphql:
    enabled: true
    execution_mode: proxyOnly
    version: "2"
    playground:
      enabled: true
      path: "/playground"
  proxy:
    target_url: http://apollo-router-prod.default.svc:80
    listen_path: /
    disable_strip_slash: true
```

## Your Environment

* kubernetes
* `tyk-operator` version/commit: latest
