### ISSUE TITLE
Allow for Ingress APIs to have categories

### ISSUE THREAD

**Issue by g-bohncke** [TykTechnologies/tyk-operator#689]
When an api in the apidefinition has a name with tags like "myapi #demo #infra" it will result in categories in the Dashboard.
When using the ingress and apidefenition
```
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: myapideftemplate
  labels:
    name: myapi
    template: "true"
spec:
  name: "myapi #demo #infra"
  ......
```
The name is ignored and and constructed via the function: [https://github.com/TykTechnologies/tyk-operator/blob/39ff14bed1ed8b81f438821d9af443eb18985ec8/controllers/ingress_controller.go#L279](url)
```
func (r *IngressReconciler) buildAPIName(nameSpace, name, hash string) string {
	return fmt.Sprintf("%s-%s-%s", nameSpace, name, hash)
}
```
This will not allow for having categories on you ingress api's. I would like to propose to change the code to:
```
name := r.buildAPIName(ns, desired.Name, template.Spec.Name, hash)

func buildAPIName(nameSpace, ingress_name, template_name, hash string) string {
	r, _ := regexp.Compile("#\\w+")
	categories := r.FindAllString(template_name, -1)
	return fmt.Sprintf("%s-%s-%s %s", nameSpace, ingress_name, hash, strings.Join(categories, " "))
}
```

**Comment by buraksekili** [comment]
hi @g-bohncke, thanks for providing a great enhancement report. We truly appreciate your input and would like to address this request.
Upon reviewing your suggestion internally within the team, as a solution, we are considering parsing an annotation from the Ingress object, such as `tyk.io/categories`, which will contain an array of categories or a string including all categories in one string. These categories would then be added to the generated API Definitions (or OAS). Our logic behind this approach comes from the fact that in Tyk, there are two methods of defining APIs: the classic Tyk API Definition and the OAS API Definition. In the future, Tyk Operator will also support OAS API Definitions alongside classic Tyk API Definitions. Given the differences in how categories are handled between OAS and classic API Definitions, consolidating them into one central location in Ingress would ease management and ensure consistency across both types of API Definitions.

So, what we thought looks like the following:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tyk-ingress
  annotations:
    kubernetes.io/ingress.class: tyk
    tyk.io/template: apidefinition-template
    tyk.io/categories: "#demo #infra1" # it will be either a string
    tyk.io/categories: # or an array of string
    - "#demo"
    - "#infra1"
spec:
   # rest of the Ingress Spec
```

Please let us know if you have any suggestions.
