### ISSUE TITLE
apidef: introduce udg support

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-operator#98]
Using ApiDefinition custom resources, it should be possible to stitch APIs together & publish them as a GraphQL API.
It should be extensible enough to support new data-sources as they become available in the underlying libraries.
This is particularly challenging, because each data-source has different configurations. In this regard, we may need to strongly type each data-source type, then recreate the `interface` or `json.RawMessage` when calling the Tyk APIs.

---

Data Sources to support OOTB:

- [x] External GraphQLData Source
- [x] External HTTP JSON Source
- [ ] Internal (Tyk-Managed) GraphQLData Source
- [ ] Internal (Tyk-Managed) HTTP JSON Source
- [ ] Extensible to support new data sources as they are introduced to underlying library, whilst maintaining benefit of strong typing & validation

---

- [ ] introduce new types if needed
- [ ] generate CRDs
- [ ] documentation in context of ./config/samples
- [ ] README example
- [ ] tests

Non-Goals:

- Security Policies for GraphQL protection will be addressed as a separate feature.

Example:

```
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: composed
spec:
  name: composed
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: https://countries.trevorblades.com
    listen_path: /composed
    strip_listen_path: true
  graphql:
    enabled: true
    execution_mode: executionEngine
    schema: |                                                  <----------------- VALIDATE THIS SCHEMA INSIDE VALIDATING WEBHOOK
      type Country {
        name: String
        code: String
        enriched: RESTCountry
      }
      type Query {
        countries: [Country]
      }
      type RESTCountry {
        subregion: String
        population: Int
      }
    type_field_configurations:
      - type_name: Query
        field_name: countries
        data_source:
          kind: GraphQLDataSource
          graphql_data_source:
            method: POST
            url: https://countries.trevorblades.com
        mapping:
          disabled: true
          path: ""
      - type_name: Country
        field_name: enriched
        data_source:
          kind: HTTPJSONDataSource
          http_json_data_source:
            default_type_name: "RESTCountry"
            method: GET
            status_code_type_name_mappings:
              - status_code: 200
            url: https://restcountries.eu/rest/v2/alpha/{{ .object.code }}
        mapping:
          disabled: true
          path: ""
    playground:                           <----------------- ENABLE GRAPHQL PLAYGROUND (SAME / SHARED WITH GRAPHQL PROXY)
      enabled: true
      path: /playground
```
